#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Idempotent + failure-safe sync of a regenerated local HTML artifact to a GitHub Pages repo.

Copy + edit SRC / REPO, then run this as a step in the SAME schedule that regenerates SRC
(e.g. append a subprocess call to the pipeline, or a 5-min Windows task). Behaviour:
  * fast path: source mtime <= last SUCCESSFUL push -> skip (no empty commit)
  * has update: copy -> git add -> git commit (may be no-op) -> git push (retried)
  * ONLY on a verified successful push do we stamp the source mtime; on failure we keep the old
    stamp so the next run MUST re-push. Never swallow a pending update behind a false "synced".
Edit the two paths below and the push-branch name (this host's `git init` default is master; the
Pages repo uses main).
"""
import os, time, shutil, subprocess, datetime

SRC   = r"E:\path\to\artifact.html"          # <- regenerated by your schedule
REPO  = r"{{HERMES_HOME_PARENT}}\my-publish-repo"       # <- git repo with remote=origin (public, Pages on)
STAMP = os.path.join(REPO, ".last_synced")
BRANCH = "main"
PUSH_RETRIES = 5
PUSH_WAIT_S  = 8


def sh(cmd, timeout=120):
    return subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, timeout=timeout)


def main():
    now = datetime.datetime.now()
    if not os.path.exists(SRC):
        print(f"{now:%H:%M} source missing, skip")
        return

    mtime = os.path.getmtime(SRC)
    last = 0.0
    if os.path.exists(STAMP):
        try:
            last = float(open(STAMP).read().strip())
        except Exception:
            last = 0.0

    if mtime <= last:
        print(f"{now:%H:%M} no update (src mtime {mtime:.0f} <= last-success {last:.0f}), skip")
        return

    shutil.copyfile(SRC, os.path.join(REPO, "index.html"))
    sh(["git", "add", "index.html"])
    sh(["git", "commit", "-m", f"auto: refresh {now:%m-%d %H:%M}"])  # may be a no-op; harmless

    pushed = False
    for i in range(1, PUSH_RETRIES + 1):
        p = sh(["git", "push", "origin", BRANCH])
        if p.returncode == 0:
            pushed = True
            break
        print(f"  push {i}/{PUSH_RETRIES} failed: {p.stderr.strip()[:80]}")
        time.sleep(PUSH_WAIT_S)

    if pushed:
        # only stamp on a VERIFIED successful push, so a network flake cannot strand the update
        open(STAMP, "w").write(str(mtime))
        print(f"{now:%H:%M} synced, remote now at src mtime={mtime:.0f}")
    else:
        # keep the OLD stamp -> next run re-pushes; never mark a failed push as done
        print(f"{now:%H:%M} sync FAILED (keeping old stamp, will retry next run), pending mtime={mtime:.0f}")


if __name__ == "__main__":
    main()
